# Generated by Django 5.2 on 2025-04-09 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_recruitment_new'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruitment',
            old_name='dscript',
            new_name='type',
        ),
    ]
