# Generated by Django 5.2 on 2025-04-09 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_rename_dscript_recruitment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruitment',
            old_name='type',
            new_name='scription',
        ),
    ]
