# Generated by Django 5.2 on 2025-04-09 08:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_rename_type_recruitment_scription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
