# Generated by Django 5.2 on 2025-04-20 17:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_new_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='scription',
            field=ckeditor.fields.RichTextField(default='Chưa có mô tả'),
            preserve_default=False,
        ),
    ]
