# Generated by Django 5.2 on 2025-04-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_recruitment_scription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='scription',
            field=models.TextField(null=True),
        ),
    ]
